### PR TITLE
Add license file

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/jaraco/keyrings.alt/pull/8

Picked commit from PR ( https://github.com/jaraco/keyrings.alt/pull/8 ) and added the license to the manifest. Hoping a fresh PR will help.

cc @stratakis @astaric

### CODE REVIEW

**Comment by jaraco** [comment]
Thanks for this re-submit, and sorry for the hassle. I accepted #8 instead once I got to a machine that could accept a PR with test failures (which weren't the fault of the submission).

I've got a refresh of the package skeleton which should address the test failures, so cfca5e4 should become unnecessary.

And as for the manifest, I think that's also unnecessary as this project relies on the Git repo for the project manifest (via setuptools_scm).

**Comment by jaraco** [comment]
1.2 is being [released now](https://travis-ci.org/jaraco/keyrings.alt/builds/181650461). When that release lands, would you confirm that the sdist suits your needs?

**Comment by stratakis** [comment]
Thanks for addressing this. As I am involved with packaging downstream, for Fedora there are strict rules in regards to licenses. So when keyrings.alt was introduced as a dependency for wheel (which is in turn dependency for the way we compile python), it couldn't be included at the repositories due to the license issue so I had to patch wheel to remove the dependency. Anyway now this is fixed so the issue is resolved.

**Comment by jakirkham** [comment]
Yep, looks fine. Thanks for doing this, @jaraco .

**Pull request closed without merging**
