### PR TITLE
Provide a license file

### PR DESCRIPTION
**Pull request by stratakis**
While MIT is mentioned as a license for the project, the file is actually not included.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please add it to `MANIFEST.in` too?

**Comment by jakirkham** [comment]
cc @astaric

**Comment by jaraco** [comment]
https://github.com/jaraco/skeleton/issues/1

**Comment by jakirkham** [comment]
Much like our discussion in issue ( https://github.com/pypa/setuptools/issues/612 ), I maintain the same opinion for the same reason here. To briefly list them, here they are.

1. The MIT license requires it. (Quote below)
2. As noted by Ian, legal departments depend on this structure of licensing to determine what can be used.

Given the legwork has already be done in this PR, please reconsider. Would happily address the `MANIFEST.in` in a follow up PR.
<br>

```
The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.
```

ref: https://opensource.org/licenses/MIT

**Comment by jaraco** [comment]
As long as there are people willing to maintain it and it doesn't cause me any additional burden, I'll allow it to exist.

**Comment by jaraco** [comment]
Well already, I'm stymied. The tests are failing so I can't merge from my phone. I'll have to revisit this another time.

**Pull request merged**
